<?php
/**
 * Copyright © 2016 SalesIds. All rights reserved.
 * See COPYING.txt for license details.
 *
 */

// @codingStandardsIgnoreFile
?>
<?php
    $services = $this->getRenderingServices();
    $i = 0;
?>
<div class="salesids-socialshare <?php echo $this->getServiceType() ?> <?php echo $this->getDisplayType() . $this->getScreenPosition() ?>"
    style="<?php echo $this->getBarStyle() ?>"
>
    <?php foreach ($services as $service): ?>
        <div
            class="<?php echo $this->getServiceContainerClass($services, $service, $i++) ?>"
            style="<?php echo $this->getServiceContainerStyle($service)?>"
            <?php echo $this->getDynamicStyle($service) ?>
        >
            <?php echo $service->toHtml() ?>
        </div>
    <?php endforeach; ?>
    <script type="text/x-magento-init">
        {
            "div.service-item": {
                "socialShareService": {}
            }
        }
    </script>
</div>