<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty
 */
?>
<?php if ($block->isMsgVisible()): ?>
    <div class="availability only" title="<?php /* @escapeNotVerified */ echo __('%1 Available', ($block->getStockQtyLeft())) ?>">
        <?php /* @escapeNotVerified */ echo __('%1 Availiable', "<strong>{$block->getStockQtyLeft()}</strong>") ?>
    </div>
<?php endif ?>
