<?php
/**
 * Copyright © 2016 SalesIds. All rights reserved.
 * See COPYING.txt for license details.
 *
 */

// @codingStandardsIgnoreFile
?>
<?php
    $services = $this->getHiddenRenderingServices ();
    $i = 0;
?>
<a
	href="#"
	id="<?php echo $this->getLinkId() ?>"
    title="<?php echo $this->getName() ?>"
    class="<?php echo $this->getClass() ?>"
    style="<?php echo $this->getStyle() ?>"
></a>

<div id="<?php echo $this->getModalId() ?>"
	class="no-display salesids-socialshare inline">
	<div class="services">
        <?php foreach ($services as $service): ?>
            <div
                class="<?php echo $this->getWidget()->getServiceContainerClass($services, $service, $i++) ?>"
                style="<?php echo $this->getWidget()->getServiceContainerStyle($service)?>"
            >
                <?php echo $service->toHtml() ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#<?php echo $this->getLinkId() ?>": {
            "socialShareMoreService": {
                "modalContainer": "#<?php echo $this->getModalId() ?>"
            }
        }
    }
</script>