<?php
/**
 * Copyright © 2016 SalesIds. All rights reserved.
 * See COPYING.txt for license details.
 *
 */

// @codingStandardsIgnoreFile
?>
<a
	onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,scrollbars=yes,height=600,width=600');return false;"
    href="<?php echo $this->getLinkUrl() ?>"
    title="<?php echo $this->getName() ?>"
    class="<?php echo $this->getClass() ?>"
    style="<?php echo $this->getStyle() ?>"
></a>