<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>
<?php /* @var $block \Amasty\Preorder\Block\Product\View\Preorder\ProductDefault */?>

<?php
if(!$block->canShowBlock()) {
    return;
}
?>
<script type="text/javascript">
    require(['jquery', 'Amasty_Preorder/js/product/preorder'], function($) {
        $widget = $.mage.amastyPreorder({
            aviabilityElement: $(".stock").first(),
            addToCartButton: $("#product-addtocart-button span"),
            preOrderNote: '<?=$block->getPreorderNote();?>',
            addToCartLabel: '<?=$block->getCartLabel()?>'
        });
        $widget.enable();
        var preNote = $('.product-info-stock-sku > .stock.available').html();
        $('.product-info-stock-sku > .product.attribute.sku').after('<div class="preNote">'+preNote+'</div>');
        $('.product-info-stock-sku > .stock.available').html('<span class="preorder">Pre-Order</span>');
        $('#product-addtocart-button').prop('disabled',true);
        $('.box-tocart').append('<div class="preorder-fields"><div class="preorder-bootan"><span>Pre-Order Policy</span></div><input type="checkbox" name="preorder-policy" id="checkbox-preorder"><label for="checkbox-preorder">I have read and understand the pre-order policy.</label></div>');
        $('#checkbox-preorder').change(function(){
        	if ($(this).is(":checked")) {
        		$('#product-addtocart-button').prop('disabled',false);
        	} else {
        		$('#product-addtocart-button').prop('disabled',true);
        	}
        });
    });
    require(['jquery', 'Magento_Ui/js/modal/modal'], function($, modal){
    	var options = {
    		type: 'popup',
    		responsive: true,
    		innerScroll: true,
    		clickableOverlay: true,
    		title: 'About Movie Replicas Direct Pre-Orders'
    		// buttons: [{
    		// 	text: $.mage.__('Close'),
    		// 	class: 'modalClose',
    		// 	click: function() {
    		// 		this.closeModal();
    		// 	}
    		// }]
    	};
    	$('.preorder-bootan').click(function(){
    		$('.modal-preorder').modal(options).modal('openModal');
    	});
    });
</script>
<div class="modal-preorder">
	<div class="popupSubTitles">What is a Pre-Order?</div>
	<p>A pre-order is an order that allows you to purchase an item that is coming soon. These coming soon items will be marked as “Pre-Order” and will have an expected release date. The release dates are set up by the manufacturer and are subject to change.</p>
	<div class="popupSubTitles">Why Pre-Order an item?</div>
	<p>Pre-Order pricing is locked in at the price you purchased a product for. If the price goes up you are locked in.</p>
	<p>Next, your chances of getting a product is much greater with a pre-order. At times a limited edition or a hard to find items may sell out before they actually come into stock. Pre-ordering gives you a better chance to own your favorite pop culture statues, busts, action figures &amp; collectibles at a lower risk of the possibly of not getting it at all. You may also face having to wait several months after its release, for it to become available again, if it comes into stock at all.</p>
	<p>All pre-orders are on a first come first serve basis and are filled by the original order date. It is possible for an item to be sold out even as a Pre-Order due to limited supplies. Under no circumstances will we fill an order out of sequence. If merchandise becomes sold out you will be notified and refunded in full when refunds are applicable.</p>
	<div class="popupSubTitles">How will I be charged for my Pre-Order?</div>
	<p>If you use a PayPal account, you will be charged in full at the time of purchase. All credit card / debit charge accounts will be charged at the time your Pre-Order ships. If the item is cancelled by our distributor or we are not able to allocate an item, we will notify you as soon as we find out. Please note that a charge may show up on your card immediately. This is not a charge, it is actually an authorization. Generally your statement shows the authorization as a pending transaction. The authorization is done by us, but funds are never taken from your bank or credit card company. This Authorization will drop off your card in 3 to 5 business days depending on how long your bank holds the funds. Your card will be billed at the time of shipment.</p>
	<p>Your order will only be billed at the time the order is placed if a request is made. This can be done by adding your request to the comment area when ordering.</p>
	<div class="popupSubTitles">Does Movie Replicas Direct charge a restock fee for Pre-Order cancellations?</div>
	<p>Yes, Movie Replicas Direct has the right to charge a restock fee of 10% for cancellations or returns.</p>
	<div class="popupSubTitles">When does my Pre-Order ship?</div>
	<p>Each Pre-Order item has an expected “release date” and your Pre-Order will generally ship on or around that date. Please be aware that the manufacturer may change the release date, there by making the release and ship date change. Sometimes our site does not reflect the new date, but we will do our best to update the information, when we find something out.If a Pre-Order release date changes, we will ship the order on or around that new release date.</p>
	<div class="popupSubTitles">If I order in stock merchandise with my Pre-Order, when will the items ship?</div>
	<p>All items will ship together when your Pre-Order arrives. If you should need the in stock items to be shipped right away a second order should be placed. One containing the In Stock items and another with the Pre-Order items. Note: We must do this to help keep our shipping costs down.</p>
	<div class="popupSubTitles">What if a Pre-Order item is Pre-Order Sold Out?</div>
	<p>If for any reason your merchandise becomes unavailable, we will credit to your PayPal account, if applicable. You will be contacted via email and your order will be cancelled.</p>
	<div class="popupSubTitles">Why would my Pre-Order be cancelled?</div>
	<p>There may be times when we do not receive our entire allocation of a product from our Distributor. When this occurs, we fulfill orders based the oldest order date through the most recent order date (first come, first serve). Your order may be cancelled if we are not allocated enough merchandise to fulfill your order.</p>
	<p>Our Distributors may choose to cancel a product line if pre-sales are low and could cancel a Pre-Ordered item or product line. If this occurs we will contact you, cancel your order, and credit your credit or PayPal account in full. Please be aware that we may offer an item as a Pre-Order, but we cannot guarantee the item will be made and cannot be held responsible if the Manufacturer decides to cancel a product or product line.</p>
</div>