<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>
<?php /* @var $block \Amasty\Preorder\Block\Product\View\Preorder\ProductDefault */?>

<?php
if(!$block->canShowBlock()) {
    return;
}
?>
<script type="text/javascript">
    require(['jquery', 'Amasty_Preorder/js/product/preorder'], function($) {
        $widget = $.mage.amastyPreorder({
            aviabilityElement: $(".stock").first(),
            addToCartButton: $("#product-addtocart-button span"),
            preOrderNote: '<?=$block->getPreorderNote();?>',
            addToCartLabel: '<?=$block->getCartLabel()?>'
        });
        $widget.enable();
        var preNote = $('.product-info-stock-sku > .stock.available').html();
        $('.product-info-stock-sku > .product.attribute.sku').after('<div class="preNote">'+preNote+'</div>');
        $('.product-info-stock-sku > .stock.available').html('<span class="preorder">Pre-Order</span>');
    });
</script>
