<?php
/**
 * Copyright © 2016 SalesIds. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="admin__field field field-<?php echo $block->getElement()->getHtmlId() ?>"
    data-ui-id="widget-instance-edit-tab-properties-fieldset-element-form-field-<?php echo $block->getElement()->getHtmlId() ?>"
>
    <?php echo $block->getElement()->getLabelHtml() ?>
    <div id="<?php echo $this->element->getClass() ?>" class="admin__field-control control">
         <?php echo $block->getBlock()->toHtml() ?>
    </div>
</div>