<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php

/**
*  General template for displaying group of blocks devided into sections
*/

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
    <div class="sections <?php /* @escapeNotVerified */ echo $groupCss ?>">
        <?php $layout = $block->getLayout(); ?>
        <div class="section-items <?php /* @escapeNotVerified */ echo $groupCss ?>-items" data-mage-init='<?php /* @escapeNotVerified */ echo $groupBehavior ?>'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="section-item-title <?php /* @escapeNotVerified */ echo $groupCss ?>-item-title" data-role="collapsible">
                    <a class="<?php /* @escapeNotVerified */ echo $groupCss ?>-item-switch" data-toggle="switch" href="#<?php /* @escapeNotVerified */ echo $alias; ?>"><?php /* @escapeNotVerified */ echo $label; ?></a>
                </div>
                <div class="section-item-content <?php /* @escapeNotVerified */ echo $groupCss ?>-item-content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content"><?php /* @escapeNotVerified */ echo $html; ?></div>
            <?php endforeach;?>
            <div class="mobile-menu-button"><span>Menu</span></div>
<!-- START SEARCH CODE -->
			<?php $helper = $this->helper('Magento\Search\Helper\Data'); ?>
			<div class="block block-search">
			    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
			    <div class="block block-content">
			        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
			            <div class="field search">
			                <div class="control">
			                    <input id="search"
			                           data-mage-init='{"quickSearch":{
			                                "formSelector":"#search_mini_form",
			                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
			                                "destinationSelector":"#search_autocomplete"}
			                           }'
			                           type="text"
			                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
			                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
			                           placeholder="<?php /* @escapeNotVerified */ echo __('Search...'); ?>"
			                           class="input-text"
			                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
			                           role="combobox"
			                           aria-haspopup="false"
			                           aria-autocomplete="both"
			                           autocomplete="off"/>

			                <button type="submit"
			                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
			                        class="action search">
			                </button>
			                    <div id="search_autocomplete" class="search-autocomplete"></div>
			                </div>
			            </div>
			            
			        </form>
			    </div>
			</div>
<!-- END SEARCH CODE -->
        </div>
    </div>
<?php endif; ?>