<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>
<?php
/**
 * @var $block \Amasty\Preorder\Block\Product\ListProduct\Preorder
 */
?>

<div class="amasty-preorder-note"><?=$block->getPreorderNote();?></div>
<script type="text/javascript">
    require(['jquery', 'Magento_Catalog/js/catalog-add-to-cart'], function($) {
        var cartLabel = '<?=$block->getCartLabel();?>';
        var $button = $('input[name="product"][value="<?=$block->getProduct()->getId();?>"]').parent().find('.tocart')[0];
        if(!$button){
            return;
        }
        $button = $($button);
        while ($button.children().length > 0) {
            $button = $button.children();
        }
        $.mage.catalogAddToCart.prototype.options.addToCartButtonTextDefault = cartLabel;
        $button.html(cartLabel);
    });
    require(['jquery'], function($){
    	
    });
</script>