<?php
/**
 * Copyright © 2016 SalesIds. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<table class="admin__control-table <?php echo $block->getContainer()->getElementName()?>" id="<?php echo $block->getElement()->getHtmlId() ?>">
    <thead>
        <tr id="<?php echo $block->getContainer()->getElementName()?>-table">
            <th class="col-draggable"></th>
            <th class="data-grid-th"><?php echo __('Social element') ?></th>
            <th class="data-grid-th"><?php echo __('Enabled') ?></th>
        </tr>
    </thead>
    <tbody data-role="<?php echo $block->getContainer()->getElementName()?>-container"></tbody>
</table>

<script id="<?php echo $block->getContainer()->getElementName()?>-row-template" type="text/x-magento-template">
    <tr>
        <td class="col-draggable">
            <?php if (!$block->getReadOnly()): ?>
                <div data-role="draggable-handle" class="draggable-handle" title="<?php /* @escapeNotVerified */ echo __('Sort Service'); ?>"></div>
            <?php endif; ?>
            <input data-role="order" type="hidden" name="parameters[conditions][<?php echo $block->getContainer()->getElementName() ?>][<%- data.service_id %>][position]"  value="<%- data.sort_order %>" <?php if ($block->getReadOnly()): ?> disabled="disabled"<?php endif; ?>/>
        </td>
        <td class="control-table-text"><span class="icon <%- data.icon %>" style="background-color:<%- data.color %>;"></span><%- data.name %></td>
        <td class="control-table-actions-cell">
            <div class="switcher">
                <input class="admin__actions-switch-checkbox" id="input-check-<?php echo $block->getContainer()->getElementName() ?>-<%- data.service_id %>" type="checkbox" value="1" name="parameters[conditions][<?php echo $block->getContainer()->getElementName() ?>][<%- data.service_id %>][selected]" style="display:none;" <%- data.checked %>>
                <label class="admin__actions-switch-label" for="input-check-<?php echo $block->getContainer()->getElementName() ?>-<%- data.service_id %>">
                    <span style="display:inline" class="admin__actions-switch-text" data-text-on="<?php echo __('Yes') ?>" data-text-off="<?php echo __('No') ?> "></span>
                </label>
            </div>
        </td>
    </tr>
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "services": {
                "table": "<?php echo $block->getContainer()->getElementName()?>-table",
                "rowTemplate": "#<?php echo $block->getContainer()->getElementName()?>-row-template",
                "container": "<?php echo $block->getContainer()->getElementName()?>-container",
                "services": <?php /* @noEscape */ echo json_encode($block->getServices(), JSON_HEX_QUOT); ?>,
                "isSortable":  <?php echo (int)(!$block->getReadOnly()) ?>,
                "isReadOnly": <?php echo (int)$block->getReadOnly(); ?>
            }
        }
    }
</script>