<?php
/**
 * Top menu for store
 *
 * @var $block \Ey\MegaMenu\Block\Page\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<div class="menu-close"><div class="menu-close-x"></div><span>Close</span></div>
<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
    <div id="mega-menu-container"></div>
</nav>
<div class="mobile-questions">
<?php echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::Ey/header-questions.phtml')->toHtml();?>
</div>
<ul class="mobile-userops">
<?php echo $this->getLayout()->createBlock('Magento\Customer\Block\Account\AuthorizationLink')->setTemplate('account/link/authorization.phtml')->toHtml();?>
<li>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
   echo '<a href="'.$this->getBaseUrl().'customer/account/">My Account</a>';
} else {
	echo '<a href="'.$this->getBaseUrl().'customer/account/create/">Create An Account</a>';
}
?>
</li>
</ul>