<?php
/**
 * Copyright © 2016 SalesIds. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @see  https://developers.facebook.com/docs/plugins/share-button#example
 */

// @codingStandardsIgnoreFile
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "<?php echo $this->getSrc() ?>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!-- Your like button code -->
<div class="fb-share-button" data-href="<?php echo $this->getServiceUrl() ?>" data-layout="<?php echo $this->getNumberedType() ?>"></div>