<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="security-wrapper">
	<div class="security-item">
		<div class="sitems">
			<div class="sitem-head">Secure Shopping</div>
			<div class="sitem-sub">256 Bit Encryption</div>
		</div>
	</div>
	<div class="security-item">
		<div class="sitems">
			<div class="sitem-head">Questions?</div>
			<div class="sitem-sub">Call Us: <a href="tel:8886987767">(888) 698-7767</a></div>
		</div>
	</div>
	<div class="security-item">
		<div class="sitems">
			<div class="sitem-head">International Shipping</div>
			<div class="sitem-sub">See Details</div>
		</div>
	</div>
</div>

