<div class="footer content">
	<div class="grid-wrapper">
		<div class="grid-item">
			<i class="fa fa-phone" aria-hidden="true"></i><a href="tel:8886987767">(888) 698-7767</a> M-F 9am-5pm EST
		</div>
		<div class="grid-item">
			<img src="<?php echo $this->getViewFileUrl('images/footer-cards.png');?>" alt="Credit Card Graphic" />
			<img src="<?php echo $this->getViewFileUrl('images/footer-encrypt.png');?>" alt="Secure Shopping, 256-bit Encryption" />
		</div>
		<div class="grid-item">
			Copyright &copy; <script type="text/javascript">var today=new Date();document.write(today.getFullYear());</script> Movie Replicas Direct. All Rights Reserved. Site Design by <a href="http://www.eystudios.com" target="_blank">EYStudios</a>.
		</div>
	</div>
</div>
