<a href="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
<a href="twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
<a href="blog"><img src="<?php echo $this->getViewFileUrl('images/blogger-icon.png'); ?>" alt="Blogger"/></a>
<a href="pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
<a href="googleplus"><i class="fa fa-google-plus" aria-hidden="true"></i></a>