<a href="https://www.facebook.com/pages/Movie-Replicas-Direct/105482109971" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
<a href="https://twitter.com/moviereplica" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
<a href="http://moviereplicasdirect.blogspot.com/" target="_blank"><img src="<?php echo $this->getViewFileUrl('images/blogger-icon.png'); ?>" alt="Blogger"/></a>
<a href="https://www.pinterest.com/moviereplicas/" target="_blank"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
<a href="https://plus.google.com/117431987304943097181" target="_blank"><i class="fa fa-google-plus" aria-hidden="true"></i></a>