<a href="facebook" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
<a href="twitter" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
<a href="blog" target="_blank"><img src="<?php echo $this->getViewFileUrl('images/blogger-icon.png'); ?>" alt="Blogger"/></a>
<a href="pinterest" target="_blank"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
<a href="googleplus" target="_blank"><i class="fa fa-google-plus" aria-hidden="true"></i></a>